server:
  replicaCount: 1
  config:
    persistence:
      numHistoryShards: 512
      datastores:
        default:
          sql:
            pluginName: postgres12
            driverName: postgres12
            databaseName: temporal
            connectAddr: "postgres-postgresql.temporal.svc.cluster.local:5432"
            connectProtocol: tcp
            user: temporal
            existingSecret: temporal-db-secret
            secretKey: password
            createDatabase: false
            manageSchema: false
        visibility:
          sql:
            pluginName: postgres12
            driverName: postgres12
            databaseName: temporal_visibility
            connectAddr: "postgres-postgresql.temporal.svc.cluster.local:5432"
            connectProtocol: tcp
            user: temporal
            existingSecret: temporal-db-secret
            secretKey: password
            createDatabase: false
            manageSchema: false
