/**
 * Runtime configuration.
 *
 * In production (k8s): nginx serves /config.js generated by docker-entrypoint.sh
 * from ConfigMap env vars. window.__APP_CONFIG__ is populated before this module loads.
 *
 * In local dev (Vite): /config.js is a static placeholder with an empty object,
 * so window.__APP_CONFIG__.apiBaseUrl is undefined and the import.meta.env fallback
 * is used instead. No Docker required for local development.
 */

declare global {
  interface Window {
    __APP_CONFIG__?: {
      /** HTTP base path. Prod: "/api". Dev: undefined → import.meta.env fallback. */
      apiBaseUrl?: string;
    };
  }
}

// Vite inlines import.meta.env at build time (dev only).
// These are never present at runtime in the production bundle.
interface ImportMetaEnv {
  readonly VITE_WS_BASE_URL?: string;
}

const cfg = window.__APP_CONFIG__;

// ---------------------------------------------------------------------------
// API base URL (HTTP)
// Prod: "/api"  (relative — same-origin via Ingress, no CORS needed)
// Dev:  "http://localhost:8000/api"  (derived from VITE_WS_BASE_URL)
// ---------------------------------------------------------------------------
export const API_BASE_URL: string =
  cfg?.apiBaseUrl ??
  ((import.meta.env as ImportMetaEnv).VITE_WS_BASE_URL?.replace(/^ws/, 'http') ??
    'http://localhost:8000/api');

// ---------------------------------------------------------------------------
// WebSocket base URL
// Prod (apiBaseUrl="/api"):                derived from window.location
// Local k8s (apiBaseUrl="http://host/api"): swap scheme (http→ws / https→wss)
// Vite dev (no cfg):                        VITE_WS_BASE_URL or localhost fallback
// ---------------------------------------------------------------------------
function deriveWsBase(apiBaseUrl: string): string {
  // Absolute URL — split host from path so backend can live on a different port.
  if (/^https?:\/\//.test(apiBaseUrl)) {
    return apiBaseUrl.replace(/^http/, 'ws');
  }
  // Relative path — same-origin via Ingress proxy.
  return `${location.protocol === 'https:' ? 'wss' : 'ws'}://${location.host}${apiBaseUrl}`;
}

export const WS_BASE_URL: string = cfg?.apiBaseUrl
  ? deriveWsBase(cfg.apiBaseUrl)
  : ((import.meta.env as ImportMetaEnv).VITE_WS_BASE_URL ??
      'ws://localhost:8000/api');
