/**
 * Runtime configuration.
 *
 * In production (k8s): nginx serves /config.js generated by docker-entrypoint.sh
 * from ConfigMap env vars. window.__APP_CONFIG__ is populated before this module loads.
 *
 * In local dev (Vite): /config.js is a static placeholder with an empty object,
 * so window.__APP_CONFIG__.apiBaseUrl is undefined and the import.meta.env fallback
 * is used instead. No Docker required for local development.
 */

declare global {
  interface Window {
    __APP_CONFIG__?: {
      /** HTTP base path. Prod: "/api". Dev: undefined → import.meta.env fallback. */
      apiBaseUrl?: string;
      /** Runtime feature flag, controlled via ConfigMap without image rebuild. */
      useTemporalApi?: boolean;
    };
  }
}

// Vite inlines import.meta.env at build time (dev only).
// These are never present at runtime in the production bundle.
interface ImportMetaEnv {
  readonly VITE_WS_BASE_URL?: string;
}

const cfg = window.__APP_CONFIG__;

// ---------------------------------------------------------------------------
// API base URL (HTTP)
// Prod: "/api"  (relative — same-origin via Ingress, no CORS needed)
// Dev:  "http://localhost:8000/api"  (derived from VITE_WS_BASE_URL)
// ---------------------------------------------------------------------------
export const API_BASE_URL: string =
  cfg?.apiBaseUrl ??
  ((import.meta.env as ImportMetaEnv).VITE_WS_BASE_URL?.replace(/^ws/, 'http') ??
    'http://localhost:8000/api');

// ---------------------------------------------------------------------------
// WebSocket base URL
// Prod: "wss://host/api" or "ws://host/api" (derived from window.location)
// Dev:  "ws://localhost:8000/api"  (from VITE_WS_BASE_URL)
// ---------------------------------------------------------------------------
export const WS_BASE_URL: string = cfg?.apiBaseUrl
  ? `${location.protocol === 'https:' ? 'wss' : 'ws'}://${location.host}${cfg.apiBaseUrl}`
  : ((import.meta.env as ImportMetaEnv).VITE_WS_BASE_URL ??
      'ws://localhost:8000/api');

// ---------------------------------------------------------------------------
// Feature flag — kept for future rollback capability via ConfigMap.
// Currently unused in components (USE_TEMPORAL_API was removed in step 5
// of the Temporal migration), but available for re-introduction without
// an image rebuild.
// ---------------------------------------------------------------------------
export const USE_TEMPORAL_API: boolean = cfg?.useTemporalApi ?? true;
