apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diploma-postgres
  namespace: argocd
spec:
  project: default
  source:
    chart: postgresql
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: "18.6.6"
    helm:
      values: |
        auth:
          username: temporal
          password: temporal
          database: temporal
        primary:
          persistence:
            enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
