apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  labels:
    app.kubernetes.io/part-of: operations
data:
  TEMPORAL_HOST: "temporal-frontend.temporal.svc.cluster.local:7233"
  TEMPORAL_NAMESPACE: "default"
  TASK_QUEUE: "operations"
  REDIS_URL: "redis://redis-master.redis.svc.cluster.local:6379"
