temporal:
  server:
    replicaCount: 1
    config:
      persistence:
        default:
          driver: cassandra
          cassandra:
            hosts:
              - temporal-cassandra
            keyspace: temporal
            replicationFactor: 1
        visibility:
          driver: cassandra
          cassandra:
            hosts:
              - temporal-cassandra
            keyspace: temporal_visibility
            replicationFactor: 1
  cassandra:
    config:
      cluster_size: 3
  prometheus:
    enabled: false
  grafana:
    enabled: false
  elasticsearch:
    enabled: false
