apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: diploma
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Kulunchick/diploma
    targetRevision: main
    path: deploy/argocd/production
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
