apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temporal
  namespace: argocd
spec:
  project: default
  source:
    chart: temporal
    repoURL: https://go.temporal.io/helm-charts
    targetRevision: "1.2.0"
    helm:
      values: |
        server:
          replicaCount: 1
          config:
            persistence:
              numHistoryShards: 512
              datastores:
                default:
                  sql:
                    pluginName: postgres12
                    driverName: postgres12
                    databaseName: temporal
                    connectAddr: "postgres-postgresql.temporal.svc.cluster.local:5432"
                    connectProtocol: tcp
                    user: temporal
                    existingSecret: temporal-db-secret
                    secretKey: password
                    createDatabase: false
                    manageSchema: false
                visibility:
                  sql:
                    pluginName: postgres12
                    driverName: postgres12
                    databaseName: temporal_visibility
                    connectAddr: "postgres-postgresql.temporal.svc.cluster.local:5432"
                    connectProtocol: tcp
                    user: temporal
                    existingSecret: temporal-db-secret
                    secretKey: password
                    createDatabase: false
                    manageSchema: false
        prometheus:
          enabled: false
        grafana:
          enabled: false
        elasticsearch:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: temporal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
