[project]
name = "coursework-operations"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Kulunchick", email = "nikolikrasovski@gmail.com" }
]
dependencies = [
    "numpy>=2.2.4",
    "fastapi>=0.115.12",
    "websockets>=15.0.1",
    "uvicorn>=0.34.2",
    "assignment-solver>=0.5.0",
    "cffi>=1.17.1",
    "temporalio>=1.7.0",
    "redis>=5.0.0",
]
readme = "README.md"
requires-python = ">= 3.8"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.rye]
managed = true
virtual = true
dev-dependencies = []

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = ["src/coursework_operations"]
